CONNECT TO HROPS;


ALTER TABLE "HROPS_SCHEMA"."POSITION" ALTER COLUMN "POSITION_ID" SET GENERATED AS IDENTITY ( START WITH 0 INCREMENT BY 1 NO CACHE ) ;
ALTER TABLE "HROPS_SCHEMA"."POSITION" ALTER COLUMN "POSITION_ID" RESTART WITH 17;


ALTER TABLE "HROPS_SCHEMA"."QUALIFICATION" ALTER COLUMN "QUAL_ID" SET GENERATED AS IDENTITY ( START WITH 0 INCREMENT BY 1 NO CACHE ) ;
ALTER TABLE "HROPS_SCHEMA"."QUALIFICATION" ALTER COLUMN "QUAL_ID" RESTART WITH 19;


ALTER TABLE "HROPS_SCHEMA"."APPLICATION" ALTER COLUMN "APPLICATION_ID" SET GENERATED AS IDENTITY ( START WITH 0 INCREMENT BY 1 NO CACHE ) ;
ALTER TABLE "HROPS_SCHEMA"."APPLICATION" ALTER COLUMN "APPLICATION_ID" RESTART WITH 15;


ALTER TABLE "HROPS_SCHEMA"."DEPARTMENT" ALTER COLUMN "DEPT_ID" SET GENERATED AS IDENTITY ( START WITH 0 INCREMENT BY 1 NO CACHE ) ;
ALTER TABLE "HROPS_SCHEMA"."DEPARTMENT" ALTER COLUMN "DEPT_ID" RESTART WITH 11;


ALTER TABLE "HROPS_SCHEMA"."EMPLOYEE" ALTER COLUMN "EMPLOYEE_ID" SET GENERATED AS IDENTITY ( START WITH 0 INCREMENT BY 1 NO CACHE ) ;
ALTER TABLE "HROPS_SCHEMA"."EMPLOYEE" ALTER COLUMN "EMPLOYEE_ID" RESTART WITH 31;


ALTER TABLE "HROPS_SCHEMA"."ATTENDANCE" ALTER COLUMN "ID" SET GENERATED AS IDENTITY ( START WITH 0 INCREMENT BY 1 NO CACHE ) ;
ALTER TABLE "HROPS_SCHEMA"."ATTENDANCE" ALTER COLUMN "ID" RESTART WITH 31;


ALTER TABLE "HROPS_SCHEMA"."LEAVE" ALTER COLUMN "LEAVE_ID" SET GENERATED AS IDENTITY ( START WITH 0 INCREMENT BY 1 NO CACHE ) ;
ALTER TABLE "HROPS_SCHEMA"."LEAVE" ALTER COLUMN "LEAVE_ID" RESTART WITH 7;



-- DDL Statements for foreign keys on Table "HROPS_SCHEMA"."EMPLOYEE"


ALTER TABLE "HROPS_SCHEMA"."EMPLOYEE" 

	ADD CONSTRAINT "EMPLOYEE_POSITION_ID_FK" FOREIGN KEY

		("POSITION_ID")

	REFERENCES "HROPS_SCHEMA"."POSITION"

		("POSITION_ID")

	ON DELETE NO ACTION

	ON UPDATE NO ACTION

	ENFORCED

	ENABLE QUERY OPTIMIZATION;



ALTER TABLE "HROPS_SCHEMA"."EMPLOYEE" 

	ADD CONSTRAINT "EMPLOYEE_QUAL_ID_FK" FOREIGN KEY

		("QUAL_ID")

	REFERENCES "HROPS_SCHEMA"."QUALIFICATION"

		("QUAL_ID")

	ON DELETE NO ACTION

	ON UPDATE NO ACTION

	ENFORCED

	ENABLE QUERY OPTIMIZATION;



-- DDL Statements for foreign keys on Table "HROPS_SCHEMA"."ATTENDANCE"



ALTER TABLE "HROPS_SCHEMA"."ATTENDANCE" 

	ADD CONSTRAINT "ATTENDANCE_EMPLOYEE_ID_FK" FOREIGN KEY

		("EMPLOYEE_ID")

	REFERENCES "HROPS_SCHEMA"."EMPLOYEE"

		("EMPLOYEE_ID")

	ON DELETE NO ACTION

	ON UPDATE NO ACTION

	ENFORCED

	ENABLE QUERY OPTIMIZATION;



-- DDL Statements for foreign keys on Table "HROPS_SCHEMA"."LEAVE"



ALTER TABLE "HROPS_SCHEMA"."LEAVE" 

	ADD CONSTRAINT "LEAVE_EMPLOYEE_ID_FK" FOREIGN KEY

		("EMPLOYEE_ID")

	REFERENCES "HROPS_SCHEMA"."EMPLOYEE"

		("EMPLOYEE_ID")

	ON DELETE NO ACTION

	ON UPDATE NO ACTION

	ENFORCED

	ENABLE QUERY OPTIMIZATION;


COMMIT WORK;



CONNECT RESET;



TERMINATE;



-- USER is: DB2ADMIN

-- Specified SCHEMA is: HROPS_SCHEMA

-- Creating DDL for table(s)



-- Schema name is ignored for the Federated Section

;
